### ISSUE TITLE
Debug for unions is unsound, exposes uninitialized memory

### ISSUE THREAD

**Issue by LlewVallis** [magiclen/educe#13]
Using `#[derive(Educe)` and `#[educe(Debug)]` on a union that may contain uninitialized bytes produces a debug implementation that has undefined behavior from safe code (excluding the `unsafe` block produced by the macro itself).

Here is a minimum reproduction:

```rust
use std::mem::MaybeUninit;
use educe::Educe;

#[derive(Educe)]
#[educe(Debug)]
union U {
    field: MaybeUninit<[u8; 256]>,
}

fn main() {
    let u = U { field: MaybeUninit::uninit() };
    println!("{:?}", u);
}
```

Reading uninitialized bytes, even as `[u8]`, is UB, which can be verified with Miri and in the [docs for `MaybeUninit`](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html). This will happily print out uninitialized bytes from the stack on my machine.

Unless I'm missing something this also has the potential to be a security issue since leaking uninitialized bytes can be dangerous, for example leaking passwords in freed memory, although I don't know how often people are exposing `Debug` representations for unions.

For reference here is the macro output:

```rust
impl core::fmt::Debug for U {
    #[inline]
    fn fmt(&self, formatter: &mut core::fmt::Formatter) -> core::fmt::Result {
        let mut builder = formatter.debug_tuple("U");
        let size = core::mem::size_of::<Self>();
        let data = unsafe {
            { core::slice::from_raw_parts(self as *const Self as *const u8, size) }
        };
        builder.field(&data);
        builder.finish()
    }
}
```

**Comment by magiclen** [comment]
Maybe for union we can force developers to use `#[educe(Debug(unsafe))]`.

**Comment by LlewVallis** [comment]
Yeah good idea, that way anyone who is already using the feature in a way they are sure is safe can continue to do so without having to rework anything.

Maybe the plain `#[educe(Debug)]` syntax could raise a warning or an error explaining the issue. It might also be worth considering a more elaborated keyword used to silence the issue than `unsafe`, but I can't think of what that might be at the moment.
