### ISSUE TITLE
Version 0.5.12 contains breaking changes.

### ISSUE THREAD

**Issue by DenuxPlays** [magiclen/educe#25]
Refer to

- https://github.com/SeaQL/sea-query/issues/781
- https://github.com/financrr/financrr-app/tree/fc1c9c7f8a9d853f4923285090e28b5f0c61791f

**Comment by tyt2y3** [comment]
Sorry, I opened another issue at #27 . May be you can close this?

**Comment by timothee-haudebourg** [comment]
I can confirm that 0.5.12 introduces breaking changes, it's affecting my [`rdf-types`](https://github.com/timothee-haudebourg/rdf-types) library that does not compile anymore. Could you yank this version?

**Comment by schungx** [comment]
Yes, it also seems to break `sea-orm`...

**Comment by DenuxPlays** [comment]
> Sorry, I opened another issue at #27 . May be you can close this?

Nice but I think these are 2 different issues.
0.5.12 still contains breaking changes so this version needs to be yanked (imo)

**Comment by magiclen** [comment]
Sorry for any inconvenience. I've already yanked version 0.5.12. I will look into this issue later when I am available.

**Comment by ijackson** [comment]
I think this ticket can be closed.  @magiclen was right to yank 0.5.12 and release 0.6.x instead.

(I do think we need to do better about #27, see comments in #26.  And, sorry for precipitating this mess.)
