### ISSUE TITLE
`#[derive(Serde)]` shorthand for `#[derive(Serialize, Deserialize)]`

### ISSUE THREAD

**Issue by alecmocatta** [magiclen/educe#7]
I have a few types with so many derives that `rustfmt` overflows them:

```rust
#[derive(
    Default,
    Clone,
    Copy,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    EnumIter,
    Serialize,
    Deserialize,
    Debug
)]
```

It occurred to me that it might be worth a shorthand to combine `Serialize` and `Deserialize`. So my derives will look a lot nicer. Until there are even more and they overflow again...

```rust
#[derive(Default, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, EnumIter, Serde, Debug)]
```

This crate, which I love for minimising boilerplate, occurred to me as a potential home for a `Serde` derive that does this, so I thought I'd suggest it here.

**Comment by magiclen** [comment]
`Serialize` and `Deserialize` are not built-in traits in Rust.

If `educe` supported `serde`, the code would be

```rust
#[derive(Educe)]
#[educe(Serialize, Deserialize)]
struct Struct {
    f1: u8
}
```

Then, I don't see why I want to use `educe` to implement `Serialize` and `Deserialize`.
