### ISSUE TITLE
`educe` uses legacy (^1) version of `syn` crate.

### ISSUE THREAD

**Issue by A1-Triard** [magiclen/educe#8]

**Comment by magiclen** [comment]
I'm planing to update the `syn` crate to ^2 (though `NestedMeta` has been removed).

**Comment by A1-Triard** [comment]
> though `NestedMeta` has been removed

Yep. I tried to update `syn` after I created the issue, but I found that it is difficult to do it without detailed knowledge about `educe` attributes structure, because it requires to reimplement parsing :-(
